### ISSUE TITLE
[Bug]: Bounties not showing up (no Epic Valheim)

### ISSUE THREAD

**Issue by Sythalin** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#11]
### How are you playing the game?

Single Player - No Server

### What happened?

Valheim + Epic Loot = bounties
Valheim + Epic Loot + DVEAB = no bounties

### To Reproduce

Install only Epic Loot and DVEAB.  Go to a trader and there are no bounties.

### Relevant log output

```shell
[Debug  :Digitalroot] Removing default bounties
[Debug  :Digitalroot] Soft Dependencies
MonsterLabZ : False
CustomRaids : False
SpawnThat : False
RRRCore : False
RRRNpcs : False
RRRMonsters : False
RRRBetterRaids : False
Bears : False

[Debug  :Digitalroot] Adding Bounties to EpicLoot
[Debug  :Digitalroot] Loaded Bounties: 0
```

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties/files/7070098/LogOutput.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Researching

**Comment by Digitalroot** [comment]
I think I found the issue. Give if this is it, I will post am update ASAP

**Comment by Digitalroot** [comment]
v2.0.6 has been uploaded to Nexus. Thank you for reporting this.
