### ISSUE TITLE
[Bug]: Invalid bounties included for Epic Valheim

### ISSUE THREAD

**Issue by Gra-tak** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#18]
### How are you playing the game?

Multiplayer - My Client Hosts Server

### What happened?

Passive mobs can appear as bounties in the list of bounties (see screenshots for two examples).
The ones I noticed are wolf cubs, baby pigs, seagals and crows.
If you accept any of those and go the designated area, no bounty mob is spawned. Pretty sure that it's not just hidden somewhere, as I removed all trees and stones in the area in search of a baby pig.

### To Reproduce

1. Change bounties in adventuredata.json to different Gold value to make sure the mod is actually active. As far as I understand, these changes should not appear in the game since they are overwritten by this mod anyway. Steps to make sure this actually works seem to be to install via thunderstore r2mod manager (or for me do run the game in linux).
2. Wait for different bounties to appear. It's meadows and black forest only as far as I can tell.

### Screenshots

![bounties](https://user-images.githubusercontent.com/33484874/152047096-64a3cd36-699b-47ac-8e25-abb0d76ef7ba.png)

### Relevant log output

```shell
[Info   :   BepInEx] Loading [Digitalroot EpicLoot Adventure Bounties 2.1.0]
[Info   :   BepInEx] Loading [Digitalroot Valheim EpicLoot Adventure Bounties for Epic Valheim 1.2.2]
[Debug  :Digitalroot] Adding Bounties to EpicLoot
[Debug  :Digitalroot] Adding 12 bounties for Meadows
[Debug  :Digitalroot] Adding 10 bounties for Swamp
[Debug  :Digitalroot] Adding 10 bounties for Mountain
[Debug  :Digitalroot] Adding 20 bounties for BlackForest
[Debug  :Digitalroot] Adding 10 bounties for Plains
[Debug  :Digitalroot] Adding 3 bounties for Ocean
[Debug  :Digitalroot] Adding 3 bounties for Mistlands
[Debug  :Digitalroot] Loaded Bounties: 112
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Thank you for reporting this. I have an idea on why this is happening.
