### ISSUE TITLE
[Bug]: Wrong reference to RRRM_PolarSerpentSmall

### ISSUE THREAD

**Issue by bennydiamond** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#19]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

This mod seems to reference the "Frost-Brood Serpent" from RRRMonsters with wrong value.

In RRRMonsters, unit is named "RRRM_PolarSerpentSmall" while this mod has reference to "SmallPolarSerpent".
I was tipped off when I saw a bouty at the trader that displayed a creature type of rrrm_smallpolarserpent.

Also, side-note, this unit is located in the "Deep-North" subdir of RRRMonsters config while this mod seems to generate bouties instructing the player to locate the target in the Ocean. Is it a mistake or should I assume I should sail in the ocean around Deep-North biome to locate such creature?

### To Reproduce

1. Go to trader'
2. Scroll bouties
3. find a bouty relating to a Frost-Brood Serpent unit type

### Screenshots

![polar_serpent](https://user-images.githubusercontent.com/6563977/181046052-308cd183-0172-4777-8f05-c011032370c7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Should be fixed in 3.0.x
