### ISSUE TITLE
[Bug]: Bountie creatures never show up

### ISSUE THREAD

**Issue by Alatarius** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#21]
### How are you playing the game?

Single Player - No Server

### What happened?

Whenever I go to look for the creature posted in the bounty, it never shows up. I even waited for 20 in-game days and no bounty creature appeared making the bounty unable to be completed.

### To Reproduce

1. Go to Haldor and accept a bounty request
2. go to bounty site
3. Creature never appears

### Log File

Can't use the Plugin Info Mod as game will not load if installed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Two things.

First can you post your log file for when you try to load the plug-in info mod and you say the game doesn't load.

Second, the bounty system is run by the epic loot mod. My mod just adds additional bounties to it. But the actual spawning of the mobs is managed by epic loot.
