### ISSUE TITLE
[Bug]: Game crashes if Plug-in Info log installed

### ISSUE THREAD

**Issue by Alatarius** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#22]
### How are you playing the game?

Single Player - No Server

### What happened?

I see my game crash whenever I have Plug-in Info installed

### To Reproduce

1. Install Plug-in Info
2. Start Game
3. watch game crash popup

If I uninstall Plug-in Info game will run as expected

### Relevant log output

```shell
Can't post log because I get this error:
"There was an error creating your Issue: body is too long, body is too long (maximum is 65536 characters)."

Also can't attach log file as dragging and dropping doesn't work on this site for me for some unknown reason and there is no upload button. Also get the same error if trying to upload an image.
```

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties/files/10333819/LogOutput.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Alatarius** [comment]
![error](https://user-images.githubusercontent.com/101660302/210286089-47c9711e-7331-4815-9a63-02354ecd32e5.png)

**Comment by Digitalroot** [comment]
I look for the attached log file. And it does show that the plug-in is loading correctly and outputting the details of all the other loaded plugins into the log file. However I do notice you are running mods that are out of date and are known to be broken. I know there's issues with bon appetit for example.

**Comment by Alatarius** [comment]
I have the latest update for Bon Appetit as was posted on Vortex and it still works just fine. The only ones that I know are out of date are the Balrond items that will never be updated and I use them still because they are just so handy and a quality of life upgrade for me. The only issue I have really had with mods is the Plug-in Info mod. Most are fine with the way they are but this is the only mod I have that crashes my game
--
Sent from Outlook Email App for Android Monday, 02 January 2023, 04:26PM -08:00 from Digitalroot  ***@***.*** :

**Comment by Digitalroot** [comment]
LMK if this is still an issue.
