### ISSUE TITLE
[Bug]:   The bounties  doesn't want to be validated

### ISSUE THREAD

**Issue by ANGRAND-Theophile** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#28]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

Good morning,

- The mod is currently active both on my server and in solo play. 

- I have no error in the CMD which manages the mods.

- When I go to see the merchant he offers me bounties, I can accept them.

- They are displayed correctly on the map with the red circle.

- When I go there the bonty boss is there.

- I can eliminate it.

- But unfortunately the bounty is not validated when the enemies are dead.

- The red circle on the map remains active. 

- But I can't return the bounty to our friend the merchant.

- Where do you think the problem could come from?

I would like to take this moment to say a big thank you for this mod which looks great.

### To Reproduce

1. Go to 'Merchant' 
2. Take 'Bounty'
3. Do the  'Bounty'
4. Nothing happens

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Figure it out?

**Comment by ANGRAND-Theophile** [comment]
Hi,

Sorry for the response time. 

The mod works very well, bounties and treasure hunting.
I changed the uploaded file manually to NexusMods.
I took the one published on ThunderStore, since the problem has been solved.

**Comment by ANGRAND-Theophile** [comment]
Hey sorry for the delay !
Yeah all is good, I uninstalled the version from nexus mod and I installed
manually from thendorstore.
It started to work. Your mod is really great, thank you very much!

Le mar. 10 déc. 2024 à 00:21, Digitalroot ***@***.***> a
écrit :
