### ISSUE TITLE
Bounties not showing

### ISSUE THREAD

**Issue by nicola-de-smet** [Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties#9]
**Describe the bug**
With the last version, the bounties aren't showing anymore. I only get the test one.

**To Reproduce**
With last version go the haldor and see

**Expected behavior**
Bounties should appear

**Screenshots**
Here the error I get in bepinEx
![ErrorValheim](https://user-images.githubusercontent.com/17121308/129181588-d3731b97-15be-47fb-9a88-fe28811654ff.PNG)

**Comment by Digitalroot** [comment]
Would you upload/attach your `LogOutput.log` file that contains the error? It can be found at `C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\LogOutput.log`

**Comment by nicola-de-smet** [comment]
Sure this is it !
[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EpicLoot.Adventure.Bounties/files/6980612/LogOutput.log)

**Comment by Digitalroot** [comment]
``` 
[Warning:   BepInEx] Plugin [PlantEverything 1.7.1] targets a wrong version of BepInEx (5.4.15.0) and might not work until you update
[Warning:   BepInEx] Plugin [Jotunn 2.2.3] targets a wrong version of BepInEx (5.4.15.0) and might not work until you update
```

Update BepInEx to 5.4.15.0

**Comment by Digitalroot** [comment]
It looks like Digitalroot.Valheim.EpicLoot.Bounties didn't even try to load. 

This is what the log looks like when the mod runs. This is missing from your log. 
```
[All    :Digitalroot.Valheim.EpicLoot.Bounties] Digitalroot.Valheim.EpicLoot.Bounties.PatchObjectDBCopyOtherDB.Postfix
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Removing default bounties
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Soft Dependencies 
MonsterLabZ : True
CustomRaids : True
SpawnThat : True
RRRCore : True
RRRNpcs : True
RRRMonsters : True
RRRBetterRaids : True
Friendlies : True
Bears : True

[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding Bounties to EpicLoot
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 23 bounties for Meadows
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 33 bounties for Swamp
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 27 bounties for Mountain
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 15 bounties for BlackForest
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 42 bounties for Plains
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 9 bounties for AshLands
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 8 bounties for DeepNorth
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 1 bounties for Ocean
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 5 bounties for Mistlands
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 5 bounties for Mountain
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 2 bounties for DeepNorth
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 2 bounties for Swamp
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 5 bounties for Mountain
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 10 bounties for BlackForest
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 5 bounties for Plains
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 2 bounties for AshLands
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 2 bounties for DeepNorth
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 1 bounties for Ocean
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 5 bounties for Mistlands
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 9 bounties for Meadows
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 6 bounties for Swamp
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 8 bounties for Mountain
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 16 bounties for BlackForest
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 4 bounties for Plains
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 9 bounties for AshLands
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 9 bounties for DeepNorth
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 3 bounties for Ocean
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Adding 13 bounties for Mistlands
[Debug  :Digitalroot.Valheim.EpicLoot.Bounties] Loaded Bounties: 279
```

Try editing your `BepInEx.cfg` file. Find the `[Logging.Disk]` section and set `LogLevels = All`

Run the game as you did before and post the `LogOutput.log` again. Maybe there will be more info. 

Also add this mod, https://www.nexusmods.com/valheim/mods/1302. It will write to the log details on which mods are loaded and if there were any issues loading them.

**Comment by Digitalroot** [comment]
I do not see anything in the `Valheim Diving Mod 1.1.5` that jumps out at me as a problem.

**Comment by nicola-de-smet** [comment]
Well I donwload the last version of your mod cause I was using the epic valheim config pack and it seems to work so maybe I mess with something by installing and configuring. I'll test like you recommend me next monday to be sure cause I'm away from home this week-end

**Comment by Digitalroot** [comment]
This was also reported here, https://www.nexusmods.com/valheim/mods/1409?tab=bugs
I found the bug. There is a new version of both DLLs that remove the dependency on Friendlies. Which resolve this issue. 

Fixed in:
Digitalroot.Valheim.EpicLoot.Adventure.Bounties 2.0.4
Digitalroot.EpicLoot.Bounties.EpicValheim 1.0.1
